spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: quizApp

jpa:
  hibernate:
    ddl-auto: update # You can use "validate", "create", "create-drop", etc.
  show-sql: false # Set to true for debugging, but false in production
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

#  sql:
#    init:
#      mode: always # you won't do this in prod, I'm just doing this for demo purposes